algo = input ('Digital algo: ')
print ('O seu tipo primitivo é', type(algo))
print ('Só tem espaços?', algo.isspace())
print ('É um números?', algo.isnumeric())
print ('É um alfabético?', algo.isalpha())
print ('É alfanumérico?', algo.isalnum())
print ('Está em maiúsculas?', algo.isupper())
print ('Está em minúsculas?', algo.islower())
print ('Está capitalizada?', algo.istitle())